import Head from "next/head";
import HomeComponent from "~/components/contextComponents";
import { HomeContextProvider } from "~/context/homeContext";
import DefaultLayout from "~/layout";

const ContextPage = () => {
  return (
    <>
      <Head>
        <title>t3-hello-world</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomeComponent />
    </>
  );
};

ContextPage.getLayout = function getLayout(page: JSX.Element) {
  return (
    <HomeContextProvider>
      <DefaultLayout>{page}</DefaultLayout>
    </HomeContextProvider>
  );
};

export default ContextPage;
