import Head from "next/head";
import HomeComponent from "~/components/home";

export default function Home() {
  return (
    <>
      <Head>
        <title>t3-hello-world</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomeComponent />
    </>
  );
}
