import Head from "next/head";
import ZustandComponent from "~/components/zustand";
import DefaultLayout from "~/layout";

const ZustandPage = () => {
  return (
    <>
      <Head>
        <title>t3-hello-world</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ZustandComponent />
    </>
  );
};

ZustandPage.getLayout = function getLayout(page: JSX.Element) {
  return <DefaultLayout>{page}</DefaultLayout>;
};

export default ZustandPage;
